### ISSUE TITLE
ask for CMakeLists.txt file 

### ISSUE THREAD

**Issue by qixuxiang** [fanyang16120029/SSD-Single-Sot-Detector-in-CUDA#1]
Hi ,Thanks for your awesome code share, I notice that there is not file named `CMakeLists.txt` for compiling code. Would you please provide a copy file of it , Thanks a lot!

**Comment by fanyang16120029** [comment]
Hi. CmakeList.txt is already uploaded.

**Comment by qixuxiang** [comment]
Thanks a lot! Have a nice day^_^
